const stuff = [
    {
        "parentid": 10,
        "childid": 10.1,
        "accountname": "Revenue",
        "period": "2019-01-01T00:00:00",
        "ftypeid": null,
        "relatedaccountid": null,
        "rate": null,
        "amounts_per_child_account_per_year": 0.0,
        "cumulative_over_year_amounts_per_child_account": 0.00,
        "cumulative_childaccounts_over_year_per_parent_account": 0.00,
        "cumulative_relation": 0.00
    },
    {
        "parentid": 10,
        "childid": 10.1,
        "accountname": "Revenue",
        "period": "2020-01-01T00:00:00",
        "ftypeid": null,
        "relatedaccountid": null,
        "rate": null,
        "amounts_per_child_account_per_year": 500.0,
        "cumulative_over_year_amounts_per_child_account": 500.00,
        "cumulative_childaccounts_over_year_per_parent_account": 500.00,
        "cumulative_relation": 500.00
    },
    {
        "parentid": 10,
        "childid": 10.1,
        "accountname": "Revenue",
        "period": "2021-01-01T00:00:00",
        "ftypeid": null,
        "relatedaccountid": null,
        "rate": 1000.0,
        "amounts_per_child_account_per_year": 1000.0,
        "cumulative_over_year_amounts_per_child_account": 1500.00,
        "cumulative_childaccounts_over_year_per_parent_account": 1500.00,
        "cumulative_relation": 1500.00
    },
    {
        "parentid": 10,
        "childid": 10.1,
        "accountname": "Revenue",
        "period": "2022-01-01T00:00:00",
        "ftypeid": null,
        "relatedaccountid": null,
        "rate": 2000.0,
        "amounts_per_child_account_per_year": 2000.0,
        "cumulative_over_year_amounts_per_child_account": 3500.00,
        "cumulative_childaccounts_over_year_per_parent_account": 3500.00,
        "cumulative_relation": 3500.00
    },
    {
        "parentid": 40,
        "childid": 40.1,
        "accountname": "G&A",
        "period": "2020-01-01T00:00:00",
        "ftypeid": 1.0,
        "relatedaccountid": 2000.2,
        "rate": null,
        "amounts_per_child_account_per_year": -100.0,
        "cumulative_over_year_amounts_per_child_account": -100.00,
        "cumulative_childaccounts_over_year_per_parent_account": -100.00,
        "cumulative_relation": -100.00
    },
    {
        "parentid": 40,
        "childid": 40.1,
        "accountname": "G&A",
        "period": "2021-01-01T00:00:00",
        "ftypeid": 1.0,
        "relatedaccountid": 2000.2,
        "rate": null,
        "amounts_per_child_account_per_year": null,
        "cumulative_over_year_amounts_per_child_account": null,
        "cumulative_childaccounts_over_year_per_parent_account": null,
        "cumulative_relation": null
    },
    {
        "parentid": 40,
        "childid": 40.1,
        "accountname": "G&A",
        "period": "2022-01-01T00:00:00",
        "ftypeid": 1.0,
        "relatedaccountid": 2000.2,
        "rate": null,
        "amounts_per_child_account_per_year": null,
        "cumulative_over_year_amounts_per_child_account": null,
        "cumulative_childaccounts_over_year_per_parent_account": null,
        "cumulative_relation": null
    },
    {
        "parentid": 2000,
        "childid": 2000.1,
        "accountname": "Change in Short Term Assets",
        "period": "2019-01-01T00:00:00",
        "ftypeid": null,
        "relatedaccountid": null,
        "rate": null,
        "amounts_per_child_account_per_year": 0.0,
        "cumulative_over_year_amounts_per_child_account": 0.00,
        "cumulative_childaccounts_over_year_per_parent_account": -5.00,
        "cumulative_relation": 0.00
    },
    {
        "parentid": 2000,
        "childid": 2000.1,
        "accountname": "Change in Short Term Assets",
        "period": "2020-01-01T00:00:00",
        "ftypeid": null,
        "relatedaccountid": null,
        "rate": null,
        "amounts_per_child_account_per_year": 50.0,
        "cumulative_over_year_amounts_per_child_account": 50.00,
        "cumulative_childaccounts_over_year_per_parent_account": 45.00,
        "cumulative_relation": 50.00
    },
    {
        "parentid": 2000,
        "childid": 2000.1,
        "accountname": "Change in Short Term Assets",
        "period": "2021-01-01T00:00:00",
        "ftypeid": null,
        "relatedaccountid": null,
        "rate": null,
        "amounts_per_child_account_per_year": null,
        "cumulative_over_year_amounts_per_child_account": null,
        "cumulative_childaccounts_over_year_per_parent_account": null,
        "cumulative_relation": null
    },
    {
        "parentid": 2000,
        "childid": 2000.1,
        "accountname": "Change in Short Term Assets",
        "period": "2022-01-01T00:00:00",
        "ftypeid": null,
        "relatedaccountid": null,
        "rate": null,
        "amounts_per_child_account_per_year": null,
        "cumulative_over_year_amounts_per_child_account": null,
        "cumulative_childaccounts_over_year_per_parent_account": null,
        "cumulative_relation": null
    },
    {
        "parentid": 2000,
        "childid": 2000.2,
        "accountname": "Write Ups (Downs) on Short Term Assets",
        "period": "2019-01-01T00:00:00",
        "ftypeid": null,
        "relatedaccountid": null,
        "rate": null,
        "amounts_per_child_account_per_year": -5.0,
        "cumulative_over_year_amounts_per_child_account": -5.00,
        "cumulative_childaccounts_over_year_per_parent_account": -5.00,
        "cumulative_relation": -5.00
    },
    {
        "parentid": 2000,
        "childid": 2000.2,
        "accountname": "Write Ups (Downs) on Short Term Assets",
        "period": "2020-01-01T00:00:00",
        "ftypeid": null,
        "relatedaccountid": null,
        "rate": null,
        "amounts_per_child_account_per_year": -5.0,
        "cumulative_over_year_amounts_per_child_account": -5.00,
        "cumulative_childaccounts_over_year_per_parent_account": 45.00,
        "cumulative_relation": -5.00
    },
    {
        "parentid": 2000,
        "childid": 2000.2,
        "accountname": "Write Ups (Downs) on Short Term Assets",
        "period": "2021-01-01T00:00:00",
        "ftypeid": null,
        "relatedaccountid": null,
        "rate": null,
        "amounts_per_child_account_per_year": null,
        "cumulative_over_year_amounts_per_child_account": null,
        "cumulative_childaccounts_over_year_per_parent_account": null,
        "cumulative_relation": null
    },
    {
        "parentid": 2000,
        "childid": 2000.2,
        "accountname": "Write Ups (Downs) on Short Term Assets",
        "period": "2022-01-01T00:00:00",
        "ftypeid": null,
        "relatedaccountid": null,
        "rate": null,
        "amounts_per_child_account_per_year": null,
        "cumulative_over_year_amounts_per_child_account": null,
        "cumulative_childaccounts_over_year_per_parent_account": null,
        "cumulative_relation": null
    },
    {
        "parentid": 3000,
        "childid": 3000.1,
        "accountname": "Investments",
        "period": "2019-01-01T00:00:00",
        "ftypeid": null,
        "relatedaccountid": null,
        "rate": null,
        "amounts_per_child_account_per_year": 0.0,
        "cumulative_over_year_amounts_per_child_account": 0.00,
        "cumulative_childaccounts_over_year_per_parent_account": 0.00,
        "cumulative_relation": 0.00
    },
    {
        "parentid": 3000,
        "childid": 3000.1,
        "accountname": "Investments",
        "period": "2020-01-01T00:00:00",
        "ftypeid": null,
        "relatedaccountid": null,
        "rate": null,
        "amounts_per_child_account_per_year": 300.0,
        "cumulative_over_year_amounts_per_child_account": 300.00,
        "cumulative_childaccounts_over_year_per_parent_account": 190.00,
        "cumulative_relation": 300.00
    },
    {
        "parentid": 3000,
        "childid": 3000.1,
        "accountname": "Investments",
        "period": "2021-01-01T00:00:00",
        "ftypeid": null,
        "relatedaccountid": null,
        "rate": null,
        "amounts_per_child_account_per_year": null,
        "cumulative_over_year_amounts_per_child_account": null,
        "cumulative_childaccounts_over_year_per_parent_account": null,
        "cumulative_relation": null
    },
    {
        "parentid": 3000,
        "childid": 3000.1,
        "accountname": "Investments",
        "period": "2022-01-01T00:00:00",
        "ftypeid": null,
        "relatedaccountid": null,
        "rate": null,
        "amounts_per_child_account_per_year": null,
        "cumulative_over_year_amounts_per_child_account": null,
        "cumulative_childaccounts_over_year_per_parent_account": null,
        "cumulative_relation": null
    },
    {
        "parentid": 3000,
        "childid": 3000.2,
        "accountname": "Write Ups (Downs) on Long Term Assets",
        "period": "2019-01-01T00:00:00",
        "ftypeid": null,
        "relatedaccountid": null,
        "rate": null,
        "amounts_per_child_account_per_year": 0.0,
        "cumulative_over_year_amounts_per_child_account": 0.00,
        "cumulative_childaccounts_over_year_per_parent_account": 0.00,
        "cumulative_relation": 0.00
    },
    {
        "parentid": 3000,
        "childid": 3000.2,
        "accountname": "Write Ups (Downs) on Long Term Assets",
        "period": "2020-01-01T00:00:00",
        "ftypeid": null,
        "relatedaccountid": null,
        "rate": null,
        "amounts_per_child_account_per_year": -10.0,
        "cumulative_over_year_amounts_per_child_account": -10.00,
        "cumulative_childaccounts_over_year_per_parent_account": 190.00,
        "cumulative_relation": -10.00
    },
    {
        "parentid": 3000,
        "childid": 3000.2,
        "accountname": "Write Ups (Downs) on Long Term Assets",
        "period": "2021-01-01T00:00:00",
        "ftypeid": null,
        "relatedaccountid": null,
        "rate": null,
        "amounts_per_child_account_per_year": null,
        "cumulative_over_year_amounts_per_child_account": null,
        "cumulative_childaccounts_over_year_per_parent_account": null,
        "cumulative_relation": null
    },
    {
        "parentid": 3000,
        "childid": 3000.2,
        "accountname": "Write Ups (Downs) on Long Term Assets",
        "period": "2022-01-01T00:00:00",
        "ftypeid": null,
        "relatedaccountid": null,
        "rate": null,
        "amounts_per_child_account_per_year": null,
        "cumulative_over_year_amounts_per_child_account": null,
        "cumulative_childaccounts_over_year_per_parent_account": null,
        "cumulative_relation": null
    },
    {
        "parentid": 3000,
        "childid": 3000.3,
        "accountname": "Depreciations",
        "period": "2019-01-01T00:00:00",
        "ftypeid": null,
        "relatedaccountid": null,
        "rate": null,
        "amounts_per_child_account_per_year": 0.0,
        "cumulative_over_year_amounts_per_child_account": 0.00,
        "cumulative_childaccounts_over_year_per_parent_account": 0.00,
        "cumulative_relation": 0.00
    },
    {
        "parentid": 3000,
        "childid": 3000.3,
        "accountname": "Depreciations",
        "period": "2020-01-01T00:00:00",
        "ftypeid": null,
        "relatedaccountid": null,
        "rate": null,
        "amounts_per_child_account_per_year": -100.0,
        "cumulative_over_year_amounts_per_child_account": -100.00,
        "cumulative_childaccounts_over_year_per_parent_account": 190.00,
        "cumulative_relation": -100.00
    },
    {
        "parentid": 3000,
        "childid": 3000.3,
        "accountname": "Depreciations",
        "period": "2021-01-01T00:00:00",
        "ftypeid": null,
        "relatedaccountid": null,
        "rate": null,
        "amounts_per_child_account_per_year": null,
        "cumulative_over_year_amounts_per_child_account": null,
        "cumulative_childaccounts_over_year_per_parent_account": null,
        "cumulative_relation": null
    },
    {
        "parentid": 3000,
        "childid": 3000.3,
        "accountname": "Depreciations",
        "period": "2022-01-01T00:00:00",
        "ftypeid": null,
        "relatedaccountid": null,
        "rate": null,
        "amounts_per_child_account_per_year": null,
        "cumulative_over_year_amounts_per_child_account": null,
        "cumulative_childaccounts_over_year_per_parent_account": null,
        "cumulative_relation": null
    },
    {
        "parentid": 3000,
        "childid": 3000.4,
        "accountname": "Proceeds from sale",
        "period": "2019-01-01T00:00:00",
        "ftypeid": null,
        "relatedaccountid": null,
        "rate": null,
        "amounts_per_child_account_per_year": 0.0,
        "cumulative_over_year_amounts_per_child_account": 0.00,
        "cumulative_childaccounts_over_year_per_parent_account": 0.00,
        "cumulative_relation": 0.00
    },
    {
        "parentid": 3000,
        "childid": 3000.4,
        "accountname": "Proceeds from sale",
        "period": "2020-01-01T00:00:00",
        "ftypeid": null,
        "relatedaccountid": null,
        "rate": null,
        "amounts_per_child_account_per_year": 0.0,
        "cumulative_over_year_amounts_per_child_account": 0.00,
        "cumulative_childaccounts_over_year_per_parent_account": 190.00,
        "cumulative_relation": 0.00
    },
    {
        "parentid": 3000,
        "childid": 3000.4,
        "accountname": "Proceeds from sale",
        "period": "2021-01-01T00:00:00",
        "ftypeid": null,
        "relatedaccountid": null,
        "rate": null,
        "amounts_per_child_account_per_year": null,
        "cumulative_over_year_amounts_per_child_account": null,
        "cumulative_childaccounts_over_year_per_parent_account": null,
        "cumulative_relation": null
    },
    {
        "parentid": 3000,
        "childid": 3000.4,
        "accountname": "Proceeds from sale",
        "period": "2022-01-01T00:00:00",
        "ftypeid": null,
        "relatedaccountid": null,
        "rate": null,
        "amounts_per_child_account_per_year": null,
        "cumulative_over_year_amounts_per_child_account": null,
        "cumulative_childaccounts_over_year_per_parent_account": null,
        "cumulative_relation": null
    },
    {
        "parentid": 3000,
        "childid": 3000.5,
        "accountname": "Sold Assets Book Value",
        "period": "2019-01-01T00:00:00",
        "ftypeid": null,
        "relatedaccountid": null,
        "rate": null,
        "amounts_per_child_account_per_year": 0.0,
        "cumulative_over_year_amounts_per_child_account": 0.00,
        "cumulative_childaccounts_over_year_per_parent_account": 0.00,
        "cumulative_relation": 0.00
    },
    {
        "parentid": 3000,
        "childid": 3000.5,
        "accountname": "Sold Assets Book Value",
        "period": "2020-01-01T00:00:00",
        "ftypeid": null,
        "relatedaccountid": null,
        "rate": null,
        "amounts_per_child_account_per_year": 0.0,
        "cumulative_over_year_amounts_per_child_account": 0.00,
        "cumulative_childaccounts_over_year_per_parent_account": 190.00,
        "cumulative_relation": 0.00
    },
    {
        "parentid": 3000,
        "childid": 3000.5,
        "accountname": "Sold Assets Book Value",
        "period": "2021-01-01T00:00:00",
        "ftypeid": null,
        "relatedaccountid": null,
        "rate": null,
        "amounts_per_child_account_per_year": null,
        "cumulative_over_year_amounts_per_child_account": null,
        "cumulative_childaccounts_over_year_per_parent_account": null,
        "cumulative_relation": null
    },
    {
        "parentid": 3000,
        "childid": 3000.5,
        "accountname": "Sold Assets Book Value",
        "period": "2022-01-01T00:00:00",
        "ftypeid": null,
        "relatedaccountid": null,
        "rate": null,
        "amounts_per_child_account_per_year": null,
        "cumulative_over_year_amounts_per_child_account": null,
        "cumulative_childaccounts_over_year_per_parent_account": null,
        "cumulative_relation": null
    },
    {
        "parentid": 5000,
        "childid": 5000.1,
        "accountname": "Paid In Capital",
        "period": "2019-01-01T00:00:00",
        "ftypeid": null,
        "relatedaccountid": null,
        "rate": null,
        "amounts_per_child_account_per_year": 1000.0,
        "cumulative_over_year_amounts_per_child_account": 1000.00,
        "cumulative_childaccounts_over_year_per_parent_account": 1000.00,
        "cumulative_relation": 1000.00
    },
    {
        "parentid": 5000,
        "childid": 5000.1,
        "accountname": "Paid In Capital",
        "period": "2020-01-01T00:00:00",
        "ftypeid": null,
        "relatedaccountid": null,
        "rate": null,
        "amounts_per_child_account_per_year": -500.0,
        "cumulative_over_year_amounts_per_child_account": -500.00,
        "cumulative_childaccounts_over_year_per_parent_account": -1000.00,
        "cumulative_relation": -500.00
    },
    {
        "parentid": 5000,
        "childid": 5000.1,
        "accountname": "Paid In Capital",
        "period": "2021-01-01T00:00:00",
        "ftypeid": null,
        "relatedaccountid": null,
        "rate": null,
        "amounts_per_child_account_per_year": null,
        "cumulative_over_year_amounts_per_child_account": null,
        "cumulative_childaccounts_over_year_per_parent_account": null,
        "cumulative_relation": null
    },
    {
        "parentid": 5000,
        "childid": 5000.1,
        "accountname": "Paid In Capital",
        "period": "2022-01-01T00:00:00",
        "ftypeid": null,
        "relatedaccountid": null,
        "rate": null,
        "amounts_per_child_account_per_year": null,
        "cumulative_over_year_amounts_per_child_account": null,
        "cumulative_childaccounts_over_year_per_parent_account": null,
        "cumulative_relation": null
    },
    {
        "parentid": 5000,
        "childid": 5000.2,
        "accountname": "Dividends",
        "period": "2019-01-01T00:00:00",
        "ftypeid": null,
        "relatedaccountid": null,
        "rate": null,
        "amounts_per_child_account_per_year": 0.0,
        "cumulative_over_year_amounts_per_child_account": 0.00,
        "cumulative_childaccounts_over_year_per_parent_account": 1000.00,
        "cumulative_relation": 0.00
    },
    {
        "parentid": 5000,
        "childid": 5000.2,
        "accountname": "Dividends",
        "period": "2020-01-01T00:00:00",
        "ftypeid": null,
        "relatedaccountid": null,
        "rate": null,
        "amounts_per_child_account_per_year": -500.0,
        "cumulative_over_year_amounts_per_child_account": -500.00,
        "cumulative_childaccounts_over_year_per_parent_account": -1000.00,
        "cumulative_relation": -500.00
    },
    {
        "parentid": 5000,
        "childid": 5000.2,
        "accountname": "Dividends",
        "period": "2021-01-01T00:00:00",
        "ftypeid": null,
        "relatedaccountid": null,
        "rate": null,
        "amounts_per_child_account_per_year": null,
        "cumulative_over_year_amounts_per_child_account": null,
        "cumulative_childaccounts_over_year_per_parent_account": null,
        "cumulative_relation": null
    },
    {
        "parentid": 5000,
        "childid": 5000.2,
        "accountname": "Dividends",
        "period": "2022-01-01T00:00:00",
        "ftypeid": null,
        "relatedaccountid": null,
        "rate": null,
        "amounts_per_child_account_per_year": null,
        "cumulative_over_year_amounts_per_child_account": null,
        "cumulative_childaccounts_over_year_per_parent_account": null,
        "cumulative_relation": null
    }
];

export default stuff;